
#######################
### Variable Source ###
#######################

source = ~/.config/hypr/configs/variables.conf

###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = ALT # Sets "Opt" key as main modifier
$shiftMod = SHIFT ALT

bind = SUPER, RETURN, exec, $terminal
bind = SUPER SHIFT, RETURN, exec, $browser
bind = SUPER, SPACE, exec, $menu
bind = SUPER, Q, killactive,
bind = $mainMod, T, togglefloating,
bind = $mainMod, D, exec, discord

# what is this???
bind = $mainMod, P, pseudo, # dwindle

# Copy paste using SUPER
bind = SUPER, C, sendshortcut, CTRL, Insert,
bind = SUPER, V, sendshortcut, SHIFT, Insert,

# MacOS like navigation and text select
bind = SUPER, Left, sendshortcut, CTRL, Home,
bind = SUPER, Right, sendshortcut, CTRL, End,

bind = SUPER SHIFT, Left, sendshortcut, CTRL SHIFT, Home,
bind = SUPER SHIFT, Right, sendshortcut, CTRL SHIFT, End,

bind = ALT, Left, sendshortcut, CTRL, Left,
bind = ALT, Right, sendshortcut, CTRL, Right,

bind = ALT SHIFT, Left, sendshortcut, CTRL SHIFT, Left,
bind = ALT SHIFT, Right, sendshortcut, CTRL SHIFT, Right,

bind = SUPER, Backspace, exec, hyprctl dispatch sendshortcut SHIFT, Home, && hyprctl dispatch sendshortcut ,BackSpace,
bind = ALT, Backspace, sendshortcut, CTRL, Backspace,

binds = SUPER_R, H, exec, hyprctl dispatch sendshortcut ,Left,
binds = SUPER_R, J, exec, hyprctl dispatch sendshortcut ,Down,
binds = SUPER_R, K, exec, hyprctl dispatch sendshortcut ,Up,
binds = SUPER_R, L, exec, hyprctl dispatch sendshortcut ,Right,

# Undo/Redo with SUPER + Z / SUPER + SHIFT + Z
bind = SUPER, Z, sendshortcut, CTRL, Z,
bind = SUPER SHIFT, Z, sendshortcut, CTRL SHIFT, Z,

# Move focus with mainMod + vim motion keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r

# Turned off to make sure swapping code lines works
# bind = $mainMod, K, movefocus, u
# bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with CTRL + [0-9]
bind = CTRL, 1, movetoworkspace, 1
bind = CTRL, 2, movetoworkspace, 2
bind = CTRL, 3, movetoworkspace, 3
bind = CTRL, 4, movetoworkspace, 4
bind = CTRL, 5, movetoworkspace, 5
bind = CTRL, 6, movetoworkspace, 6
bind = CTRL, 7, movetoworkspace, 7
bind = CTRL, 8, movetoworkspace, 8
bind = CTRL, 9, movetoworkspace, 9
bind = CTRL, 0, movetoworkspace, 10

# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m output
# Screenshot a region
bind = SUPER SHIFT, 4, exec, hyprshot -m region --clipboard-only
# Screenshot a window
bind = SUPER SHIFT, 5, exec, hyprshot -m window

